### ISSUE TITLE
Fork Repo code has no defined status_code or returncode

### ISSUE THREAD

**Issue by ayush-ai8** [psvkaushik/Group50_Proj2#16]
Hi @psvkaushik ,

Can you please check the fork repo code, and make sure that it handels the return code and also the error condition. You may reference app.py to check, how its been used in other functions.

**Comment by psvkaushik** [comment]
Hello @ayush-ai8 ,

The fork_repo.py code doesn't have the error check in it because all the testing is done by different scripts(test.py and unittest.py). As mentioned in a previous issue I'll make sure to add the correct statues code to all the files to avoid any confusion. 
But I'll suggest you make a request to the forked repo to see if the repo has been forked successfully or not.

**Comment by ayush-ai8** [comment]
The return_code would do for my work, please have that integrated. Based on your comment, i places the check in app.py. Please refer to the same and let me know if it matches the idea.

**Comment by ayush-ai8** [comment]
can you confirm the status_code for fork repo of 202 would mean success? @psvkaushik

**Comment by psvkaushik** [comment]
Hello ayush-ai8,
That is correct. 202 would mean success. 
I hope this clears any issues you've regarding this script.
